### ISSUE TITLE
Closing plt before drawing causes training to stop at beginning on Windows

### ISSUE THREAD

**Issue by LarsPh** [princeton-computational-imaging/NeuLS#5]
Thank you for the great work! I am trying to train on Windows and in
https://github.com/princeton-computational-imaging/NeuLS/blob/512feac1a9cb3ae82ec1dc9ac3eee5ec728b1b0a/utils/utils.py#L253-L256
it seems that closing the plt before drawing caused the training to crash/stop. Closing the plt after drawing makes the training go on. Is this a bug or is this something weird happening on Windows?
Also is it okay to remove 
https://github.com/princeton-computational-imaging/NeuLS/blob/512feac1a9cb3ae82ec1dc9ac3eee5ec728b1b0a/utils/utils.py#L247
since that causes plot to pop up and disappear immediately during training?

**Comment by Ilya-Muromets** [comment]
Yeah, fig.canvas.draw() has odd behaviour depending on your setup (I'm working on a headless server).

Can you try:
```
plt.switch_backend('Agg')
def colorize_tensor(value, vmin=None, vmax=None, cmap=None, colorbar=False, height=9.6, width=7.2):
    """
    Convert tensor to 3-channel RGB array using colormap (similar to plt.imshow).
    """
    assert len(value.shape) == 2
    fig, ax = plt.subplots(1, 1)
    fig.set_size_inches(width, height)
    a = ax.imshow(value.detach().cpu(), vmin=vmin, vmax=vmax, cmap=cmap)
    ax.set_axis_off()
    if colorbar:
        cbar = plt.colorbar(a, fraction=0.05)
        cbar.ax.tick_params(labelsize=30)
    plt.tight_layout()

    # Convert figure to numpy array
    fig.canvas.draw()
    img = np.frombuffer(fig.canvas.tostring_rgb(), dtype=np.uint8)
    img = img.reshape(fig.canvas.get_width_height()[::-1] + (3,))
    img = img / 255.0

    plt.close(fig)
    return torch.tensor(img).permute(2, 0, 1).float()

 ```
And let me know if that works? (switching to `Agg` should stop it from drawing on screen)

**Comment by LarsPh** [comment]
That works for me (it doesn't draw on screen now on a Windows desktop). Thank you!
